#!/bin/bash
# Step-by-Step AWS EC2 Instance Creation for KidPlay Arcade
# Execute these commands one by one

echo "🚀 KidPlay Arcade - Step-by-Step AWS EC2 Deployment"
echo "==================================================="
echo ""

echo "STEP 1: Check AWS CLI Configuration"
echo "-----------------------------------"
echo "Run: aws configure list"
echo "If not configured, run: aws configure"
echo "You'll need:"
echo "- AWS Access Key ID"
echo "- AWS Secret Access Key" 
echo "- Default region (e.g., us-east-1)"
echo "- Default output format (json)"
echo ""

echo "STEP 2: Create Security Group"
echo "-----------------------------"
echo "aws ec2 create-security-group \\"
echo "    --group-name kidplay-arcade-sg \\"
echo "    --description \"Security group for KidPlay Arcade\" \\"
echo "    --region us-east-1"
echo ""

echo "# Get the Security Group ID from the output above, then:"
echo "export SG_ID=sg-xxxxxxxxxxxxxxxxx  # Replace with actual ID"
echo ""

echo "# Add security rules:"
echo "aws ec2 authorize-security-group-ingress --group-id \$SG_ID --protocol tcp --port 22 --cidr 0.0.0.0/0 --region us-east-1"
echo "aws ec2 authorize-security-group-ingress --group-id \$SG_ID --protocol tcp --port 80 --cidr 0.0.0.0/0 --region us-east-1"
echo "aws ec2 authorize-security-group-ingress --group-id \$SG_ID --protocol tcp --port 443 --cidr 0.0.0.0/0 --region us-east-1"
echo "aws ec2 authorize-security-group-ingress --group-id \$SG_ID --protocol tcp --port 3001 --cidr 0.0.0.0/0 --region us-east-1"
echo ""

echo "STEP 3: Create Key Pair"
echo "-----------------------"
echo "aws ec2 create-key-pair \\"
echo "    --key-name kidplay-arcade-key-new \\"
echo "    --query 'KeyMaterial' \\"
echo "    --output text \\"
echo "    --region us-east-1 > ~/.ssh/kidplay-arcade-key-new.pem"
echo ""
echo "chmod 400 ~/.ssh/kidplay-arcade-key-new.pem"
echo ""

echo "STEP 4: Launch EC2 Instance"
echo "---------------------------"
echo "aws ec2 run-instances \\"
echo "    --image-id ami-0c02fb55956c7d316 \\"
echo "    --count 1 \\"
echo "    --instance-type t3.micro \\"
echo "    --key-name kidplay-arcade-key-new \\"
echo "    --security-group-ids \$SG_ID \\"
echo "    --tag-specifications 'ResourceType=instance,Tags=[{Key=Name,Value=KidPlay-Arcade-New}]' \\"
echo "    --region us-east-1"
echo ""

echo "STEP 5: Get Instance Information"
echo "--------------------------------"
echo "# Get Instance ID from step 4 output, then:"
echo "export INSTANCE_ID=i-xxxxxxxxxxxxxxxxx  # Replace with actual ID"
echo ""
echo "# Wait for instance to be running:"
echo "aws ec2 wait instance-running --instance-ids \$INSTANCE_ID --region us-east-1"
echo ""
echo "# Get public IP:"
echo "aws ec2 describe-instances \\"
echo "    --instance-ids \$INSTANCE_ID \\"
echo "    --query 'Reservations[0].Instances[0].PublicIpAddress' \\"
echo "    --output text \\"
echo "    --region us-east-1"
echo ""

echo "STEP 6: Connect and Deploy"
echo "--------------------------"
echo "# SSH into the instance (replace PUBLIC_IP with actual IP):"
echo "ssh -i ~/.ssh/kidplay-arcade-key-new.pem ec2-user@PUBLIC_IP"
echo ""
echo "# Once connected, run these commands on the EC2 instance:"
echo "sudo yum update -y"
echo "curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | bash"
echo "source ~/.bashrc"
echo "nvm install 18"
echo "nvm use 18"
echo "npm install -g pm2"
echo "git clone https://github.com/ssoward/kidplay-arcade.git"
echo "cd kidplay-arcade"
echo "./deploy-aws-ec2.sh"
echo ""

echo "ALTERNATIVE: Use AWS Console"
echo "============================"
echo "If CLI doesn't work, use AWS Console:"
echo "1. Go to https://console.aws.amazon.com/ec2/"
echo "2. Click 'Launch Instance'"
echo "3. Configure:"
echo "   - Name: KidPlay-Arcade-New"
echo "   - AMI: Amazon Linux 2"
echo "   - Instance Type: t3.micro"
echo "   - Key Pair: Create new or use existing"
echo "   - Security Group: Allow ports 22, 80, 443, 3001"
echo "4. Launch and connect via SSH"
echo "5. Run deployment commands above"
echo ""

echo "🎯 Ready to start? Run the commands above step by step!"
